### PR TITLE
[WIP][13.0][IMP] avatax_connector

### PR DESCRIPTION
**Pull request by murtuzasaleh**
**WIP**

PR is for authentication based on Rest API
Partner Validate based on Rest API
Sale and Invoice (Update taxes with AvaTax) based on Rest API

### CODE REVIEW

**Comment by niyasraphy** [comment]
Does the issue with the Move line for the tax is resolved in this PR ?

**Comment by dreispt** [comment]
Yes, I expect it to be fixed during this week, with a forward port of a refactoring in a 12.0 PR.

**Review by b-kannan — COMMENTED** [review]
Should default service url be SOAP Test or REST Test?

avatax_connector/models/avalara_salestax.py -- line 50.

**Comment by dreispt** [comment]
Moved to https://github.com/OCA/account-fiscal-rule

**Pull request closed without merging**
